# Generated by Django 5.1.13 on 2025-10-07 08:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontareas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion_tarea',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.tarea'),
        ),
        migrations.AddField(
            model_name='asignacion_tarea',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.tarea'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.ManyToManyField(related_name='proyectos_asignados', to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='gestiontareas.usuario'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('pen', 'Pendiente'), ('pro', 'Progreso'), ('com', 'Completada')], default='pen', max_length=20),
        ),
        migrations.AddField(
            model_name='tarea',
            name='etiquetas',
            field=models.ManyToManyField(related_name='tareas', to='gestiontareas.etiqueta'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='gestiontareas.proyecto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
