# Generated by Django 5.1.13 on 2025-10-07 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestiontareas', '0002_asignacion_tarea_tarea_asignacion_tarea_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.usuario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='tarea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestiontareas.tarea'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_creados', to='gestiontareas.usuario'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to='gestiontareas.usuario'),
        ),
    ]
